name: Mobile CI

on:
  push:
    paths:
      - 'mobile/**'
      - '.github/workflows/mobile.yml'
  pull_request:
    paths:
      - 'mobile/**'
      - '.github/workflows/mobile.yml'

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install -g expo-cli
      - run: expo build:android --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
